### ISSUE TITLE
CSS properties order fix & TRBL

### ISSUE THREAD

**Issue by ehti** [WordPress/twentysixteen#230]
Some CSS properties were not in alphabetical order, pull request incoming.

Also, if I'm not wrong, the properties which require Top/Right/Bottom/Left values like margin/border are being ordered using the [TRBL](https://make.wordpress.org/core/handbook/best-practices/coding-standards/css/#property-ordering) standard, correct? That's what I noticed, so corrected those which were deviating from this.

**Comment by karmatosed** [comment]
I'm not convinced that you should change right, left, top, bottom like this. Lets get a second opinion, @iamtakashi what do you think?

**Comment by ehti** [comment]
Sure. And I'd like to elaborate a bit further please. Majority of the properties requiring top/bottom/right/left are currently in the TRBL order, _not_ alphabetical order. For example:

``` css
.author-info {
    border-top: 1px solid #e8e8e8;
    border-bottom: 1px solid #e8e8e8;
    clear: both;
    margin-top: 1.75em;
    padding-top: 1.75em;
    padding-bottom: 1.75em;
}
```

**Few** of them were deviating from this and were instead in alphabetical order, causing ambiguity on which order to follow. Example:

``` css
.page-content .wp-smiley,
.entry-content .wp-smiley,
.entry-summary .wp-smiley,
.comment-content .wp-smiley {
    border: none;
    margin-bottom: 0;
    margin-top: 0;
    padding: 0;
}
```

Changed these into TRBL order. I'll be happy to adjust according to what's decided.
